# Generated by Django 5.2.8 on 2025-12-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_projectcategory_sitelogo_teammember_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/featured/')),
                ('excerpt', models.CharField(blank=True, help_text='Short summary of the blog post', max_length=500)),
                ('content', models.TextField(help_text='Write your article in Markdown format')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (max 160 chars)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords (comma-separated)', max_length=255)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text="Auto-set when status becomes 'published'", null=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-published_at'], name='content_blo_publish_96cb5a_idx'), models.Index(fields=['slug'], name='content_blo_slug_441465_idx'), models.Index(fields=['status'], name='content_blo_status_e22d68_idx')],
            },
        ),
    ]
