# Generated by Django 5.2.8 on 2025-12-25 03:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date portion of created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='last_edited_date',
            field=models.DateField(auto_now=True, help_text='Date portion of updated_at'),
        ),
    ]
