# Generated by Django 5.2.8 on 2025-12-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_blogpost_created_date_blogpost_last_edited_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Company name', max_length=255)),
                ('address', models.TextField(help_text='Company physical address')),
                ('phone', models.CharField(help_text='Primary contact phone number', max_length=50)),
                ('email', models.EmailField(help_text='Primary contact email address', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Company website URL')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook profile URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL')),
                ('x_url', models.URLField(blank=True, help_text='X (Twitter) profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('custom_link_url', models.URLField(blank=True, help_text='Custom URL link')),
                ('custom_link_text', models.CharField(blank=True, help_text='Display text for custom link', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configurations',
            },
        ),
    ]
