# Generated by Django 5.2.8 on 2025-12-26 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_siteconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'ordering': ['-is_active', '-created_at'], 'verbose_name': 'Site Configuration', 'verbose_name_plural': 'Site Configurations'},
        ),
        migrations.AlterModelOptions(
            name='sitelogo',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Site Logo', 'verbose_name_plural': 'Site Logos'},
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one active configuration at a time'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Select a logo for this site configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_configs', to='content.sitelogo'),
        ),
    ]
