# Generated by Django 5.2.8 on 2025-12-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_siteconfig_options_alter_sitelogo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL (for duplicate content issues). Leave blank to use the post URL.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for featured image (for accessibility & SEO)', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary keyword for SEO optimization', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_description',
            field=models.CharField(blank=True, help_text='OpenGraph description for social sharing (optional)', max_length=160),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_title',
            field=models.CharField(blank=True, help_text='OpenGraph title for social sharing (optional, defaults to title)', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='robots_meta',
            field=models.CharField(choices=[('index, follow', 'Index & Follow (Default)'), ('noindex, follow', 'No Index, Follow'), ('index, nofollow', 'Index, No Follow'), ('noindex, nofollow', 'No Index, No Follow')], default='index, follow', help_text='Control how search engines crawl & index this page', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (max 160 chars, optimal 150-160)', max_length=160),
        ),
    ]
