# Generated by Django 5.2.8 on 2025-12-26 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_add_robust_seo_fields_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Icon class (e.g., 'fas fa-building') or emoji", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Smaller image for blog lists/cards (optional, auto-generated from featured_image if not provided)', null=True, upload_to='blog/thumbnails/'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('excerpt', models.CharField(blank=True, help_text='Short summary of the service', max_length=500)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='services/featured/')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alt text for featured image (for accessibility & SEO)', max_length=255)),
                ('content', models.TextField(help_text='Detailed service description in Markdown format')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (max 160 chars, optimal 150-160)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords (comma-separated)', max_length=255)),
                ('focus_keyword', models.CharField(blank=True, help_text='Primary keyword for SEO optimization', max_length=100)),
                ('og_title', models.CharField(blank=True, help_text='OpenGraph title for social sharing (optional, defaults to title)', max_length=100)),
                ('og_description', models.CharField(blank=True, help_text='OpenGraph description for social sharing (optional)', max_length=160)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL (for duplicate content issues). Leave blank to use the service URL.')),
                ('robots_meta', models.CharField(choices=[('index, follow', 'Index & Follow (Default)'), ('noindex, follow', 'No Index, Follow'), ('index, nofollow', 'Index, No Follow'), ('noindex, nofollow', 'No Index, No Follow')], default='index, follow', help_text='Control how search engines crawl & index this page', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Display prominently on the services page')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on services page')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text="Auto-set when status becomes 'published'", null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Service category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='content.servicecategory')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-is_featured', 'order', '-created_at'],
                'indexes': [models.Index(fields=['-published_at'], name='content_ser_publish_93e583_idx'), models.Index(fields=['slug'], name='content_ser_slug_075f59_idx'), models.Index(fields=['status'], name='content_ser_status_82649e_idx'), models.Index(fields=['-is_featured', 'order'], name='content_ser_is_feat_2e565c_idx')],
            },
        ),
    ]
