# Generated by Django 5.2.8 on 2025-12-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_add_service_model_and_blogpost_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField(blank=True, help_text="Client's physical address")),
                ('phone', models.CharField(blank=True, help_text="Client's phone number", max_length=50)),
                ('about', models.TextField(blank=True, help_text='Brief description about the client/company')),
                ('website', models.URLField(blank=True, help_text="Client's website URL")),
                ('logo', models.ImageField(blank=True, help_text="Client's company logo", null=True, upload_to='clients/logos/')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide client on website')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['order', 'name'],
            },
        ),
    ]
