# Generated by Django 5.2.8 on 2025-12-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_add_client_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='achievements_content',
            field=models.TextField(blank=True, help_text="Highlight your company's achievements and milestones"),
        ),
        migrations.AddField(
            model_name='about',
            name='achievements_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/achievements/'),
        ),
        migrations.AddField(
            model_name='about',
            name='achievements_title',
            field=models.CharField(blank=True, default='Our Achievements', max_length=200),
        ),
        migrations.AddField(
            model_name='about',
            name='goals_content',
            field=models.TextField(blank=True, help_text="List or describe your company's goals"),
        ),
        migrations.AddField(
            model_name='about',
            name='goals_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/goals/'),
        ),
        migrations.AddField(
            model_name='about',
            name='goals_title',
            field=models.CharField(blank=True, default='Our Goals', max_length=200),
        ),
        migrations.AddField(
            model_name='about',
            name='mission_content',
            field=models.TextField(blank=True, help_text="Describe your company's mission"),
        ),
        migrations.AddField(
            model_name='about',
            name='mission_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/mission/'),
        ),
        migrations.AddField(
            model_name='about',
            name='mission_title',
            field=models.CharField(blank=True, default='Our Mission', max_length=200),
        ),
        migrations.AddField(
            model_name='about',
            name='vision_content',
            field=models.TextField(blank=True, help_text="Describe your company's vision"),
        ),
        migrations.AddField(
            model_name='about',
            name='vision_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/vision/'),
        ),
        migrations.AddField(
            model_name='about',
            name='vision_title',
            field=models.CharField(blank=True, default='Our Vision', max_length=200),
        ),
    ]
