# Generated by Django 5.2.8 on 2025-12-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_projectimage_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='about_excerpt',
            field=models.TextField(blank=True),
        ),
    ]
