# Generated by Django 5.2.8 on 2025-12-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_siteconfig_about_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='clarity_id',
            field=models.CharField(blank=True, help_text='Microsoft Clarity Project ID', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='custom_tracking_code',
            field=models.TextField(blank=True, help_text='Custom tracking/analytics code snippet'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='enable_analytics',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='enable_tracking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, help_text='Facebook Pixel ID', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Google Analytics ID (GA4)', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='google_tag_manager_id',
            field=models.CharField(blank=True, help_text='Google Tag Manager ID (GTM)', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hotjar_id',
            field=models.CharField(blank=True, help_text='Hotjar Site ID', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='recaptcha_secret_key',
            field=models.CharField(blank=True, help_text='Google reCAPTCHA v3 Secret Key', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='recaptcha_site_key',
            field=models.CharField(blank=True, help_text='Google reCAPTCHA v3 Site Key', max_length=255),
        ),
    ]
