# Generated by Django 5.2.8 on 2025-12-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_optimize_to_singleton'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitelogo',
            options={'verbose_name': 'Site Logo', 'verbose_name_plural': 'Site Logo'},
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('experience_required', models.CharField(blank=True, help_text='e.g., 3-5 years', max_length=100)),
                ('salary_range', models.CharField(blank=True, help_text='Optional salary range', max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('requirements', models.TextField(help_text='Job requirements (one per line or markdown)')),
                ('responsibilities', models.TextField(blank=True, help_text='Job responsibilities (one per line or markdown)')),
                ('qualifications', models.TextField(blank=True, help_text='Required qualifications')),
                ('benefits', models.TextField(blank=True, help_text='Job benefits')),
                ('application_email', models.EmailField(blank=True, help_text='Email to receive applications', max_length=254)),
                ('application_url', models.URLField(blank=True, help_text='External application URL')),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Career',
                'verbose_name_plural': 'Careers',
                'ordering': ['-is_featured', 'order', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='content_car_slug_0c484b_idx'), models.Index(fields=['status'], name='content_car_status_8d4001_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('content', models.TextField(help_text='Notice content (supports markdown)')),
                ('excerpt', models.CharField(blank=True, help_text='Short summary', max_length=500)),
                ('attachment', models.FileField(blank=True, help_text='PDF or document attachment', null=True, upload_to='notices/attachments/')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='notices/images/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('notice_date', models.DateField(help_text='Date of the notice')),
                ('expiry_date', models.DateField(blank=True, help_text='Optional expiry date', null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_sticky', models.BooleanField(default=False, help_text='Pin to top')),
                ('order', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['-is_sticky', '-is_featured', '-notice_date', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='content_not_slug_89f055_idx'), models.Index(fields=['status'], name='content_not_status_5c8fad_idx'), models.Index(fields=['-notice_date'], name='content_not_notice__1d4f6a_idx')],
            },
        ),
    ]
