# Generated by Django 5.2.8 on 2025-12-29 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alter_sitelogo_options_career_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True)),
                ('current_position', models.CharField(blank=True, max_length=255)),
                ('current_company', models.CharField(blank=True, max_length=255)),
                ('total_experience', models.CharField(blank=True, help_text='e.g., 5 years', max_length=100)),
                ('education', models.TextField(blank=True, help_text='Educational qualifications')),
                ('cover_letter', models.TextField(help_text='Cover letter (supports HTML from Quill editor)')),
                ('resume', models.FileField(help_text='Upload resume (PDF, DOC, DOCX)', upload_to='applications/resumes/')),
                ('portfolio_url', models.URLField(blank=True, help_text='Link to portfolio/LinkedIn')),
                ('expected_salary', models.CharField(blank=True, max_length=100)),
                ('availability', models.CharField(blank=True, help_text='e.g., Immediate, 2 weeks notice', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to applicant)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='content.career')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['career', 'status'], name='content_job_career__b8c249_idx'), models.Index(fields=['-created_at'], name='content_job_created_cede93_idx'), models.Index(fields=['email'], name='content_job_email_5752c5_idx')],
            },
        ),
    ]
