# Generated by Django 5.2.8 on 2026-01-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0017_jobapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="business_hours",
            field=models.CharField(
                blank=True,
                help_text="e.g., Monday - Friday 08:00am ~ 05:00pm",
                max_length=200,
            ),
        ),
    ]
