# Generated by Django 5.2.8 on 2026-01-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_siteconfig_business_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='clarity_id',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='custom_tracking_code',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='enable_analytics',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='enable_tracking',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='facebook_pixel_id',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='google_analytics_id',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='google_tag_manager_id',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='hotjar_id',
        ),
    ]
