# Generated by Django 5.2.8 on 2026-01-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_remove_siteconfig_clarity_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='recaptcha_secret_key',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='recaptcha_site_key',
        ),
    ]
