# Generated by Django 5.2.8 on 2026-01-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_remove_siteconfig_recaptcha_secret_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='custom_link_text',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='custom_link_url',
        ),
    ]
