# Generated by Django 5.2.8 on 2026-01-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_remove_siteconfig_custom_link_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='order',
        ),
        migrations.AddField(
            model_name='banner',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('photo', 'Photo')], default='video', max_length=10),
        ),
        migrations.AddField(
            model_name='banner',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='banners/photos/'),
        ),
    ]
