# Generated by Django 5.2.8 on 2026-01-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_banner_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='photo',
        ),
    ]
