# Generated by Django 5.2.8 on 2026-01-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_remove_banner_media_type_remove_banner_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteLogo',
        ),
    ]
